image:
  - Ubuntu1804

branches:
  only:
    - master

install:
  - echo 'Install typescript'
  - npm install -g typescript
  



build:
  verbosity: detailed

build_script:
  - make refresh all



on_success:
  - echo "Done"
  - pwd
  - make coverage/lcov.info
  - ls coverage
  - bash <(curl -s https://codecov.io/bash) -f  coverage/lcov.info




