image:
  - Ubuntu1804

branches:
  only:
    - master

install:
  - npm install -g typescript


build:
  verbosity: detailed

build_script:
  - make refresh all

on_success:
  - echo "Done"
  - pwd




